export interface Doctor {
  id: number;
  userId: number;
  specialization: string;
  certifications: string[];
  maxShiftsPerDay: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
  user?: {
    id: number;
    email: string;
    name: string;
    phoneNumber: string;
    avatar?: string | null;
    status: string;
    roleId: number;
    role?: {
      id: number;
      name: string;
      description: string;
      isActive: boolean;
      createdAt: string;
      updatedAt: string;
    };
  };
  schedules?: DoctorSchedule[];
}

export interface DoctorSchedule {
  id: number;
  doctorId: number;
  date: string;
  dayOfWeek: 'SUNDAY' | 'MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY' | 'SATURDAY';
  shift: 'MORNING' | 'AFTERNOON';
  isAutoGenerated: boolean;
  swappedWithId?: number | null;
  swappedAt?: string | null;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | null;
}

export interface PaginationMeta {
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

export interface DoctorsResponse {
  data: {
    data: Doctor[];
    meta: PaginationMeta;
  };
}

export type DoctorFormValues = {
  userId: number;
  specialization?: string;
  certifications?: string[];
};

export type UpdateDoctorFormValues = {
  specialization?: string;
  certifications?: string[];
};

export type QueryDoctorFormValues = {
  search?: string;
  sortBy?: 'specialization' | 'createdAt' | 'updatedAt';
  sortOrder?: 'asc' | 'desc';
  specialization?: string;
};

export type SwapShiftsFormValues = {
  doctor1: {
    id: number;
    date: string;
    shift: 'MORNING' | 'AFTERNOON';
  };
  doctor2: {
    id: number;
    date: string;
    shift: 'MORNING' | 'AFTERNOON';
  };
};

export type GenerateScheduleFormValues = {
  startDate: string;
  doctorsPerShift: number;
};

export type ManualScheduleAssignmentFormValues = {
  doctorId: number;
  date: string;
  shift: 'MORNING' | 'AFTERNOON';
}; 